# Generated by Django 4.1.7 on 2023-03-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
